services:
  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webpos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data_webpos:/var/lib/mysql

  app:
    image: nyejoo/spring-mariadb-nginx:webpos
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/webpos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: webpos-nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data_webpos:
